In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('data/weather.formated.csv')
df2 = pd.read_csv('data/defs.csv')
df3 = pd.merge(df1, df2, left_on='日期', right_on='T_DATE')
del(df3['T_DATE'])
df3.to_csv('data/merged_data.csv', index=False)

              日期          送端          受端  平均气温/0.1℃  平均相对湿度/ 1%   \
0     2011-11-01  133427.912  127984.718        135           71
1     2011-11-02  136135.276  129876.702        131           73
2     2011-11-03  146135.962  140753.688        123           77
3     2011-11-04  148216.315  142729.717        128           78
4     2011-11-05  130378.126  125178.466        140           78
5     2011-11-06  117725.187  113162.113        129           81
6     2011-11-07  134108.701  129606.133        118           95
7     2011-11-08  124136.145  119198.374        106           95
8     2011-11-09  101445.615   97613.878        102           77
9     2011-11-10  100960.687   97407.986        101           79
10    2011-11-11  102897.187   99250.596        115           79
11    2011-11-12   95233.820   91657.624        121           77
12    2011-11-13   92857.987   90381.802        127           73
13    2011-11-14  113357.215  109336.638        120           76
14    2011-11-15  113052.737  108838.975        121           78
15    2011-11-16  114041.601  109759.502        121           74
16    2011-11-17  113897.562  109162.978        120           68
17    2011-11-18  106147.326  101858.959        117           68
18    2011-11-19  105611.787  101589.782        117           74
19    2011-11-20   99607.751   95969.133        115           74
20    2011-11-21  105330.812  101403.035        116           78
21    2011-11-22  107446.501  103238.499        107           79
22    2011-11-23  107095.712  103057.153        110           76
23    2011-11-24  114291.362  109973.634        117           78
24    2011-11-25  113638.001  109250.572        121           78
25    2011-11-26  113124.373  108802.715        120           78
26    2011-11-27  104898.387  100822.673        109           76
27    2011-11-28  115510.812  111143.326        103           74
28    2011-11-29  112007.712  107298.928        128           63
29    2011-11-30  117148.873  112647.866        124           74
...          ...         ...         ...        ...          ...
1308  2015-06-01  487459.010  460194.233        243           45
1309  2015-06-02  558793.009  526900.425        254           42
1310  2015-06-03  575866.246  541966.643        257           44
1311  2015-06-04  579407.034  544260.145        263           47
1312  2015-06-05  605558.975  568650.651        252           54
1313  2015-06-06  586691.024  551079.201        252           49
1314  2015-06-07  544589.418  514049.603        248           47
1315  2015-06-08  541134.403  509738.670        245           53
1316  2015-06-09  585719.108  551394.026        249           51
1317  2015-06-10  576109.531  544598.517        243           49
1318  2015-06-11  599169.569  561772.908        196           74
1319  2015-06-12  608312.566  571049.166        199           80
1320  2015-06-13  605116.322  568059.341        210           71
1321  2015-06-14  534671.259  504098.397        228           61
1322  2015-06-15  544400.191  509878.358        228           63
1323  2015-06-16  543534.200  509071.220        220           67
1324  2015-06-17  577205.540  540224.297        229           63
1325  2015-06-18  571187.358  533897.522        227           66
1326  2015-06-19  581841.988  542777.896        218           77
1327  2015-06-20  376220.177  354384.238        248           57
1328  2015-06-21  417134.667  390493.920        238           62
1329  2015-06-22  455532.226  425981.206        243           66
1330  2015-06-23  555456.165  518136.195        254           54
1331  2015-06-24  589011.762  551509.978        259           53
1332  2015-06-25  575879.066  544138.416        245           63
1333  2015-06-26  590497.452  557862.610        235           68
1334  2015-06-27  593322.007  560878.292        232           66
1335  2015-06-28  571092.227  540917.992        244           58
1336  2015-06-29  634979.188  602017.142        243           56
1337  2015-06-30  683714.973  645200.860        243           56

      20-20时降水量/ 0.1mm  日照时数 /0.1小时%
0                    0            92
1                32700            72
2                    0            87
3                32700            62
4                    7            63
5                   12            79
6                  149             0
7                  168             0
8                    1            57
9                    0            88
10                   0            77
11                   0            81
12                   0            97
13                   0            85
14                   0            64
15                   0            76
16                   0            96
17                   0            98
18                   0            99
19                   0            95
20                   0            78
21                   0            72
22                   0            88
23                   0            72
24                   0            82
25                   0            74
26                   0            93
27                   0            99
28               32700            16
29                   0            39
...                ...           ...
1308                 0           112
1309                 0           118
1310                 0           119
1311                 0            99
1312                10            79
1313                 0           116
1314                 0           116
1315                 0            53
1316                 0            63
1317                 0            63
1318               208             0
1319                89            29
1320             32700            20
1321             32700            72
1322                 0            98
1323                 0            61
1324                 0            56
1325                 3            69
1326               112            47
1327             32700           113
1328                40            62
1329                20            94
1330                 0           123
1331                 0           115
1332                97            71
1333                 0            71
1334                 0           106
1335             32700            96
1336                 0            92
1337                 0            69

[1338 rows x 7 columns]

## Compare two csv files and print out differences

In [8]:
with open('data/merged_data.csv', 'r') as t1, open('data/joined.csv', 'r') as t2:
    fileone = t1.readlines()
    filetwo = t2.readlines()

with open('data/update.csv', 'w') as outFile:
    for line in filetwo:
        if line not in fileone:
            outFile.write(line)